package db_tool;

public class Right {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Right.rightName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String rightname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Right.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Right.rightName
     *
     * @return the value of dbo.Right.rightName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getRightname() {
        return rightname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Right.rightName
     *
     * @param rightname the value for dbo.Right.rightName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setRightname(String rightname) {
        this.rightname = rightname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Right.Description
     *
     * @return the value of dbo.Right.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Right.Description
     *
     * @param description the value for dbo.Right.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}