package db_tool;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Role.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Role.discribe
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String discribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Role.roleName
     *
     * @return the value of dbo.Role.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Role.roleName
     *
     * @param rolename the value for dbo.Role.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Role.discribe
     *
     * @return the value of dbo.Role.discribe
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getDiscribe() {
        return discribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Role.discribe
     *
     * @param discribe the value for dbo.Role.discribe
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setDiscribe(String discribe) {
        this.discribe = discribe;
    }
}