package db_tool;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.username
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.passwold
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String passwold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.Telephone
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.Email
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.active
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.superiorName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String superiorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.User.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.username
     *
     * @return the value of dbo.User.username
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.username
     *
     * @param username the value for dbo.User.username
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.passwold
     *
     * @return the value of dbo.User.passwold
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getPasswold() {
        return passwold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.passwold
     *
     * @param passwold the value for dbo.User.passwold
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setPasswold(String passwold) {
        this.passwold = passwold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.Telephone
     *
     * @return the value of dbo.User.Telephone
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.Telephone
     *
     * @param telephone the value for dbo.User.Telephone
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.Email
     *
     * @return the value of dbo.User.Email
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.Email
     *
     * @param email the value for dbo.User.Email
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.Description
     *
     * @return the value of dbo.User.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.Description
     *
     * @param description the value for dbo.User.Description
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.active
     *
     * @return the value of dbo.User.active
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.active
     *
     * @param active the value for dbo.User.active
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.superiorName
     *
     * @return the value of dbo.User.superiorName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getSuperiorname() {
        return superiorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.superiorName
     *
     * @param superiorname the value for dbo.User.superiorName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setSuperiorname(String superiorname) {
        this.superiorname = superiorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.User.roleName
     *
     * @return the value of dbo.User.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.User.roleName
     *
     * @param rolename the value for dbo.User.roleName
     *
     * @mbggenerated Tue May 17 09:59:01 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}